from google import genai



class GeminiLLM:
    def __init__(self, api_key: str):
        self.client = genai.Client(api_key=api_key)

    def format_results(self, results):
        """
        Convert retrieved assessment dictionaries into readable text
        before sending them to Gemini.
        """

        if not results:
            return "No assessments retrieved."

        formatted = []

        for i, assessment in enumerate(results, start=1):
            formatted.append(
                f"""
Assessment {i}

Name: {assessment.get("name", "Not specified")}
Category: {assessment.get("category", "Not specified")}
Duration: {assessment.get("duration", "Not specified")}
Job Level: {assessment.get("job_level", "Not specified")}

Description:
{assessment.get("description", "Not specified")}

Skills:
{", ".join(assessment.get("skills", [])) if isinstance(assessment.get("skills"), list) else assessment.get("skills", "Not specified")}

Test Type:
{assessment.get("test_type", "Not specified")}
"""
            )

        return "\n".join(formatted)

    def generate_response(self, query, results):

        formatted_results = self.format_results(results)

        prompt = f"""
# ROLE

You are SHL Recruit AI.

Recommend ONLY from the retrieved SHL assessments.

Never invent assessments.

---

# USER QUERY

{query}

---

# RETRIEVED SHL ASSESSMENTS

{formatted_results}

---

# TASK

Recommend the best matching assessments.

Rank them.

Recommend between 3 and 5 assessments whenever possible.

Use markdown.

Use headings.

Use tables.

Maximum 350 words.

If no assessment matches, return:

# No Matching Assessments Found

No suitable SHL assessments were found.
"""

        try:

            response = self.client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
            )

            print("========== GEMINI RESPONSE ==========")
            print(response)
            print("=====================================")

            if hasattr(response, "text") and response.text:
                return response.text

            # Sometimes Gemini returns candidates instead of response.text
            try:
                candidate = response.candidates[0]
                parts = candidate.content.parts

                if parts and hasattr(parts[0], "text"):
                    return parts[0].text
            except Exception:
                pass

            return "No response generated by Gemini."

        except Exception as e:

            print("========== GEMINI ERROR ==========")
            print(e)
            print("==================================")

            return f"Gemini Error: {str(e)}"